#!/usr/bin/env php
<?php declare(strict_types=1);

// Set folder
chdir(__DIR__);

// Error logging
ini_set('log_errors', '1');
ini_set('error_log', './php_errors.log');

require __DIR__ . '/vendor/autoload.php';

// require './settings.php';

$command_tool = new IKM\MadeUpWordGenerator2\LangWordGenCommandTool();
$command_tool->run();